import type { Theme } from '@mui/material/styles'

/** Variáveis para CSS global / CSS modules (`var(--dn-*)`). Únicas para futuro toggle de tema. */
export function getLandingCssVariables(theme: Theme): Record<string, string> {
  const L = theme.landing
  const { palette: p, gradients: g, header: h, shadow: s, radius: r, spacing: sp, carousel } =
    L

  return {
    '--dn-primary': p.primaryText,
    '--dn-secondary': p.accent,
    '--dn-muted': p.muted,
    '--dn-body-bg': p.bodyBg,
    '--dn-on-light-surface': p.onLightSurface,
    '--dn-border': p.border,
    '--dn-success': p.success,
    '--dn-error': p.error,
    '--dn-gradient': g.hero,
    '--dn-gradient-soft': g.soft,
    '--dn-gradient-cta': g.ctaBanner,
    '--dn-gradient-glow': g.heroGlow,
    '--dn-gradient-hero-video-scrim': g.heroVideoScrim,
    '--dn-gradient-hero-video-scrim-mobile': g.heroVideoScrimMobile,
    '--dn-primary-dark': p.footerBg,
    '--dn-header-bg': p.headerBackdrop,
    '--dn-header-backdrop-filter': h.backdropFilter,
    '--dn-footer-muted': p.footerMuted,
    '--dn-footer-divider': p.footerDivider,
    '--dn-nav-icon': p.navIcon,
    '--dn-overlay-strong': p.overlayWhiteStrong,
    '--dn-overlay-muted': p.overlayWhiteMuted,
    '--dn-overlay-medium': p.overlayWhiteMedium,
    '--dn-glass-border': p.glassBorder,
    '--dn-glass-border-ghost': p.glassBorderGhost,
    '--dn-glass-bg': p.glassBg,
    '--dn-glass-bg-stat': p.glassBgStat,
    '--dn-glass-border-weak': p.glassBorderWeak,
    '--dn-chip-blue-bg': p.chipBlueBg,
    '--dn-icon-blue-tint': p.iconBlueTint,
    '--dn-service-card-bg': p.serviceCardBg,
    '--dn-cta-muted': p.ctaMuted,
    '--dn-header-nav': p.headerNavLink,
    '--dn-cta-bg': p.ctaBg,
    '--dn-cta-bg-hover': p.ctaBgHover,
    '--dn-cta-bg-active': p.ctaBgActive,
    '--dn-cta-text': p.ctaText,
    '--dn-cta-border-hover': p.ctaBorderHover,
    '--dn-shadow-header-cta': s.headerCta,
    '--dn-shadow-hero-aside': s.heroAside,
    '--dn-shadow-about-img': s.aboutImg,
    '--dn-shadow-card': s.card,
    '--dn-shadow-cta-ribbon': s.ctaRibbon,
    '--dn-radius-sm': `${r.sm}px`,
    '--dn-radius-md': `${r.md}px`,
    '--dn-radius-lg': `${r.lg}px`,
    '--dn-radius-xl': `${r.xl}px`,
    '--dn-radius-hero': `${r.hero}px`,
    '--dn-radius-xxl': `${r.xxl}px`,
    '--dn-radius-pill': `${r.pill}px`,
    '--dn-section-y': `${sp.sectionY}px`,
    '--dn-hero-pt': `${sp.heroTopPad}px`,
    '--dn-hero-pb': `${sp.heroBottomPad}px`,
    '--dn-carousel-muted': carousel.textMuted,
    '--dn-carousel-g1': carousel.gradientSlide1,
    '--dn-carousel-g2': carousel.gradientSlide2,
    '--dn-carousel-g3': carousel.gradientSlide3,
    '--dn-shadow-carousel-panel': s.carouselPanel,
    '--dn-shadow-carousel-heavy': s.carouselHeavy,
    '--dn-shadow-carousel-heavy-sm': s.carouselHeavySm,
    '--dn-shadow-carousel-soft': s.carouselSoft,
    '--dn-shadow-carousel-bottom': s.carouselBottom,
  }
}
